# Generated by Django 3.2.12 on 2022-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('Lua', 'Lua'), ('Rust', 'Rust'), ('Go', 'Go'), ('Julia', 'Julia')], default='0', max_length=30)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
    ]
