# Generated by Django 3.2.12 on 2022-03-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skills_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='username',
        ),
    ]
