# Generated by Django 3.2.12 on 2022-03-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_skills_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='username',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
